#!/usr/bin/python

# #######################################
# Example snippet for /getsetmetadata
# #######################################

from gaia import Gaia
import uuid


def example_get_set_metadata():
    # Create a handle for GPUdb running on local machine
    gaiadb = Gaia( encoding='BINARY', gaia_ip='127.0.0.1', gaia_port='9191' )

    # Create a data type that can be used with GPUdb's built-in POINT semantic
    # (note the attributes called 'x' and 'y')
    custom_schema = """{
                            "type":"record",
                            "name":"custom_type",
                            "fields":[
                                {"name":"x","type":"double"},
                                {"name":"y","type":"double"}
                            ]
                        }""".replace(' ','').replace('\n','')

    # Register the above data type in GPUdb
    # Need to specify the semantic 'point'
    # Annotation and labels are irrelevant for this example
    register_response = gaiadb.register_type( custom_schema, "", "", "POINT" )

    # Extract the type ID from the above response
    type_id = register_response[ 'type_id' ]

    # Create a set ID (usually it's good to ensure that the set ID is unique)
    set_id1 = "get_set_properties_example" + str( uuid.uuid1() )
    set_id2 = "get_set_properties_example" + str( uuid.uuid1() )

    # Create a new set using the above registered type (no parent ID needed)
    gaiadb.new_set(type_id = type_id, set_id = set_id1 )
    gaiadb.new_set(type_id = type_id, set_id = set_id2 )

    # Fetch the metadata of some sets
    response = gaiadb.get_set_metadata( [set_id1, set_id2] )

    print
    print "----------------------------------------------------------"
    print "Raw GPUdb get set metadata response (the maps should be empty as no metadata is generated by default; the user needs to add it): \n", response
    print
    print "Formatted /getsetmetadata response for two sets:"
    print
    print "set_ids:" # set IDs
    for set_id in response['set_ids']:
        print "\t", set_id
    print
    print "metadata_maps:" # metadata--the real return values
    for mmap in response['metadata_maps']:
        for key, val in mmap.iteritems():
            print "\t", key, ": ", val
    print
    print "status_info:" # Default wrapper JSON stuff
    for key, val in response['status_info'].iteritems():
        print "\t", key, ": ", val
    print "----------------------------------------------------------"

#   end function example_get_set_metadata
#####################################################################



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if __name__ == '__main__':
    example_get_set_metadata()
